In [1]:
# first neural network with keras tutorial
#sumber: https://machinelearningmastery.com/tutorial-first-neural-network-python-keras/
#data: https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv
#penjelasan data: https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.names

In [2]:
#install library keras, jika blm ada
#!pip install keras

In [3]:
#import library
from numpy import loadtxt
import tensorflow as tf
from tensorflow import keras

In [4]:
# load the dataset
dataset = loadtxt('pima-indians-diabetes.data.csv', delimiter=',')
dataset

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [5]:
type(dataset)
dataset.shape

(768, 9)

In [6]:
# split into input (X) and output (y) variables
X = dataset[:,0:8]
y = dataset[:,8]

In [7]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [8]:
y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [9]:
# define the keras model
model = keras.Sequential()
model.add(keras.layers.Dense(12, input_dim=8, activation='relu'))
model.add(keras.layers.Dense(8, activation='relu'))
model.add(keras.layers.Dense(1, activation='sigmoid'))

In [10]:
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [11]:
# fit the keras model on the dataset
model.fit(X, y, epochs=100, batch_size=10)

Epoch 1/100
77/77 [==============================] - 0s 694us/step - loss: 6.6396 - accuracy: 0.4310
Epoch 2/100
77/77 [==============================] - 0s 739us/step - loss: 1.1950 - accuracy: 0.5990
Epoch 3/100
77/77 [==============================] - 0s 672us/step - loss: 0.7243 - accuracy: 0.6432
Epoch 4/100
77/77 [==============================] - 0s 788us/step - loss: 0.6795 - accuracy: 0.6602
Epoch 5/100
77/77 [==============================] - 0s 735us/step - loss: 0.6620 - accuracy: 0.6497
Epoch 6/100
77/77 [==============================] - 0s 796us/step - loss: 0.6543 - accuracy: 0.6523
Epoch 7/100
77/77 [==============================] - 0s 988us/step - loss: 0.6482 - accuracy: 0.6628
Epoch 8/100
77/77 [==============================] - 0s 932us/step - loss: 0.6426 - accuracy: 0.6641
Epoch 9/100
77/77 [==============================] - ETA: 0s - loss: 0.6335 - accuracy: 0.68 - 0s 919us/step - loss: 0.6407 - accuracy: 0.6732
Epoch 10/100
77/77 [=============================

77/77 [==============================] - 0s 643us/step - loss: 0.5265 - accuracy: 0.7539
Epoch 82/100
77/77 [==============================] - 0s 684us/step - loss: 0.5264 - accuracy: 0.7409
Epoch 83/100
77/77 [==============================] - 0s 695us/step - loss: 0.5237 - accuracy: 0.7461
Epoch 84/100
77/77 [==============================] - 0s 589us/step - loss: 0.5237 - accuracy: 0.7461
Epoch 85/100
77/77 [==============================] - 0s 564us/step - loss: 0.5238 - accuracy: 0.7474
Epoch 86/100
77/77 [==============================] - 0s 591us/step - loss: 0.5208 - accuracy: 0.7539
Epoch 87/100
77/77 [==============================] - 0s 617us/step - loss: 0.5249 - accuracy: 0.7448
Epoch 88/100
77/77 [==============================] - 0s 612us/step - loss: 0.5255 - accuracy: 0.7500
Epoch 89/100
77/77 [==============================] - 0s 620us/step - loss: 0.5208 - accuracy: 0.7539
Epoch 90/100
77/77 [==============================] - 0s 604us/step - loss: 0.5206 - accuracy: 

In [12]:
# evaluate the keras model
loss, accuracy = model.evaluate(X, y)
print('Accuracy: %.2f' % (accuracy*100))

24/24 [==============================] - 0s 694us/step - loss: 0.5077 - accuracy: 0.7513
Accuracy: 75.13


In [13]:
loss

0.5077398419380188

In [14]:
#jalankan 10x, simpan akurasi, tampilkan histori akurasi dan rerata akurasi